# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir J:/Documents/323_lab9/323_lab9.cache/wt [current_project]
set_property parent.project_path J:/Documents/323_lab9/323_lab9.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo j:/Documents/323_lab9/323_lab9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib J:/Documents/323_lab9/323_lab9.srcs/sources_1/new/mips_final.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mips_final -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mips_final.dcp

catch { report_utilization -file mips_final_utilization_synth.rpt -pb mips_final_utilization_synth.pb }
